import subprocess
from pathlib import Path
import sys

sys.path.append(str(Path(__file__).resolve().parent.parent))

from readme_generator.generate_readme import generate

EXCLUDE_DIRS = [
    "--exclude-dirs",
    ".git",
    "--exclude-dirs",
    "__pycache__",
    "--exclude-dirs",
    ".idea",
    "--exclude-dirs",
    ".vscode",
    "--exclude-dirs",
    ".ipynb_checkpoints",
    "--exclude-dirs",
    ".egg-info",
    "--exclude-dirs",
    "dist",
    "--exclude-dirs",
    "_env",
    "--exclude-dirs",
    ".pytest_cache",
]

EXCLUDE_FILES = [
    "--exclude-files",
    ".pyc",
    "--exclude-files",
    ".pyo",
    "--exclude-files",
    ".pyd",
    "--exclude-files",
    ".DS_Store",
]

EXCLUDE_DIRS_LIST = [
    ".git",
    "__pycache__",
    ".idea",
    ".vscode",
    ".ipynb_checkpoints",
    ".egg-info",
    "dist",
    "_env",
    ".pytest_cache",
]

EXCLUDE_FILES_LIST = [".pyc", ".pyo", ".pyd", ".DS_Store"]


def run_cli(repo_path: str, overview: str) -> subprocess.CompletedProcess:
    cmd = [
        sys.executable,
        "-m",
        "readme_generator.generate_readme",
        "--repo-path",
        repo_path,
        "--overview",
        overview,
        *EXCLUDE_DIRS,
        *EXCLUDE_FILES,
    ]
    return subprocess.run(cmd, check=True, shell=False)


def test_generate_readme_cli() -> None:
    """Tests the CLI command for generating a README file."""
    repo_path = str(Path(__file__).resolve().parent)
    overview = "This is a sample README generated by the script."

    readme_path = Path(__file__).resolve().parent / "README.md"
    readme_generated_path = Path(__file__).resolve().parent / "README_generated.md"

    readme_path.unlink(missing_ok=True)
    run_cli(repo_path, overview)
    if not readme_path.exists():
        raise AssertionError("README.md should be created after running the CLI.")

    readme_generated_path.unlink(missing_ok=True)
    run_cli(repo_path, overview)
    if not readme_generated_path.exists():
        raise AssertionError(
            "README_generated.md should be created after running the CLI again."
        )

    readme_path.unlink(missing_ok=True)
    readme_generated_path.unlink(missing_ok=True)


def test_generate_readme_function() -> None:
    """Tests the generate function for creating a README file."""
    repo_path = str(Path(__file__).resolve().parent)
    overview = "This is a sample README generated by the function."

    readme_path = Path(__file__).resolve().parent / "README.md"
    readme_generated_path = Path(__file__).resolve().parent / "README_generated.md"

    readme_path.unlink(missing_ok=True)
    generate(
        repo_path=repo_path,
        overview=overview,
        exclude_dirs=EXCLUDE_DIRS_LIST,
        exclude_files=EXCLUDE_FILES_LIST,
    )
    if not readme_path.exists():
        raise AssertionError("README.md should be created after running the function.")

    readme_generated_path.unlink(missing_ok=True)
    generate(
        repo_path=repo_path,
        overview=overview,
        exclude_dirs=EXCLUDE_DIRS_LIST,
        exclude_files=EXCLUDE_FILES_LIST,
    )
    if not readme_generated_path.exists():
        raise AssertionError(
            "README_generated.md should be created after running the function again."
        )

    readme_path.unlink(missing_ok=True)
    readme_generated_path.unlink(missing_ok=True)
