name: Upload Python Package

on:
  push:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  black-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install black formatter
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Run black formatter
        run: |
          python -m black --check --diff --exclude "examples" .

  pytest:
    runs-on: ubuntu-latest
    needs: black-format
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest==8.4.0

      - name: Run pytest
        run: |
          python -m pytest -vs tests/

  release-build:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    needs: pytest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Build release distributions
        run: |
          python -m pip install --upgrade pip
          python -m pip install --verbose build
          python -m build --verbose

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    needs:
      - release-build
    permissions:
      id-token: write

    environment:
      name: pypi
      url: https://pypi.org/p/tree-readme

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/